### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by OberonProteus** [mozdren/ATNET2016#22]
One last error left, i tryed to google it without usable solution.

Error		Error 2019: Member Mapping specified is not valid. The type 'Edm.Int32[Nullable=False,DefaultValue=0]' of member 'Quantity' in type 'DatabaseModel.StorageItem' is not compatible with 'SqlServer.uniqueidentifier[Nullable=False,DefaultValue=]' of member 'Quantity' in type 'DatabaseModel.Store.StorageItems'.

**Comment by MartinCernohorsky** [comment]
Maybe because Quantity was set to guid. That was not correct so I changed it to int. See your .edmx model and generated class if there changes are reflected in there. If it is there EF mechanism for loding/saving stuff did not updated. Other two options are you are working with and "obsolote" branch or I am absolutly wrong. :)

**Comment by mozdren** [comment]
Quantity should be int, you are correct. You are right that the database and model has to be updated. First update database, then update edmx from the database.

**Comment by OberonProteus** [comment]
thanks, Build Succeeded
